// <auto-generated />
using System;
using APIFibra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIFibra.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APIFibra.Entities.Administrativo", b =>
                {
                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("Nivel")
                        .HasColumnType("tinyint");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("datetime2");

                    b.HasKey("Usuario");

                    b.ToTable("FibraAdministrativo");
                });

            modelBuilder.Entity("APIFibra.Entities.Ativo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Abertura")
                        .HasColumnType("real");

                    b.Property<float>("Compra")
                        .HasColumnType("real");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<float>("Fechamento")
                        .HasColumnType("real");

                    b.Property<float>("Maximo")
                        .HasColumnType("real");

                    b.Property<float>("Medio")
                        .HasColumnType("real");

                    b.Property<float>("Minimo")
                        .HasColumnType("real");

                    b.Property<string>("Negocios")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeAtivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("QCompra")
                        .HasColumnType("real");

                    b.Property<float>("QVenda")
                        .HasColumnType("real");

                    b.Property<string>("Quantidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Ultimo")
                        .HasColumnType("real");

                    b.Property<float>("Variacao")
                        .HasColumnType("real");

                    b.Property<float>("Venda")
                        .HasColumnType("real");

                    b.Property<string>("Volume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Data", "NomeAtivo");

                    b.ToTable("FibraAtivo");
                });

            modelBuilder.Entity("APIFibra.Entities.Cota", b =>
                {
                    b.Property<int>("Numcotista")
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("NumeroCotas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.HasKey("Numcotista");

                    b.ToTable("FibraCotas");
                });

            modelBuilder.Entity("APIFibra.Entities.CotaIndice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("CDB30Valor")
                        .HasColumnType("real");

                    b.Property<float>("CDB30Variacao")
                        .HasColumnType("real");

                    b.Property<bool>("CotaOficial")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCota")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFGTSVale")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFundoFibraMulticarteira")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFundoPremium")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPatrimonio")
                        .HasColumnType("datetime2");

                    b.Property<float>("IGPMValor")
                        .HasColumnType("real");

                    b.Property<float>("IGPMVariacao")
                        .HasColumnType("real");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PatrimonioLiquidoFibraMulticarteira")
                        .HasColumnType("real");

                    b.Property<float>("PatrimonioLiquidoFundoPremium")
                        .HasColumnType("real");

                    b.Property<float>("RentabilidadeAno")
                        .HasColumnType("real");

                    b.Property<float>("RentabilidadeDia")
                        .HasColumnType("real");

                    b.Property<float>("RentabilidadeMes")
                        .HasColumnType("real");

                    b.Property<float>("RentabilidadeUltimosMeses")
                        .HasColumnType("real");

                    b.Property<float>("SelicValor")
                        .HasColumnType("real");

                    b.Property<float>("SelicVariacao")
                        .HasColumnType("real");

                    b.Property<float>("TJLPValor")
                        .HasColumnType("real");

                    b.Property<float>("TJLPVariacao")
                        .HasColumnType("real");

                    b.Property<float>("ValorCota")
                        .HasColumnType("real");

                    b.Property<float>("ValorCotaPatrimonio")
                        .HasColumnType("real");

                    b.Property<float>("ValorFGTSVale")
                        .HasColumnType("real");

                    b.Property<float>("ValorFundoFibraMulticarteira")
                        .HasColumnType("real");

                    b.Property<float>("ValorFundoPremium")
                        .HasColumnType("real");

                    b.Property<int>("ValorPatrimonioAtual")
                        .HasColumnType("int");

                    b.Property<int>("ValorPatrimonioMedio")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("FibraCotaIndice");
                });

            modelBuilder.Entity("APIFibra.Entities.Noticia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<short>("Grupo")
                        .HasColumnType("smallint");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Data");

                    b.ToTable("FibraNoticias");
                });

            modelBuilder.Entity("APIFibra.Entities.Recadastro", b =>
                {
                    b.Property<int>("Numcotista")
                        .HasColumnType("int");

                    b.Property<string>("AutorizadoCpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AutorizadoFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AutorizadoInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("AutorizadoNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BancoConta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BancoNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BancoNumero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BancoTipoConta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaixaPostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConhecimentoFinanceiro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CpfConjuge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEmail")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("DesempenhoCargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmitirExtrato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndComp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntidadeTrabalhoCnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntidadeTrabalhoCodigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntidadeTrabalhoNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntidadeTrabalhoTelefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FiliacaoMae")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FiliacaoPai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("IdentEmissao")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentOrgao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentTipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalNascimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nacionalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeConjuge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OcupacaoProfissional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperaTerceiros")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("OutrasRendas")
                        .HasColumnType("real");

                    b.Property<float?>("Patrimonio")
                        .HasColumnType("real");

                    b.Property<DateTime?>("PerfilData")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerfilInvestidor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PessoaPolitica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poderes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoliticoCargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoliticoCpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PoliticoFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PoliticoInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("PoliticoNatureza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoliticoNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoliticoOrgao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoliticoVinculo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcuradorCpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcuradorFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcuradorInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcuradorNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profissao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proposito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegimeBens")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("RemuneracaoMensal")
                        .HasColumnType("real");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransmissaoOrdens")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Numcotista");

                    b.ToTable("FibraRecadastro");
                });
#pragma warning restore 612, 618
        }
    }
}
